# Generated by Django 5.1.1 on 2024-09-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='static/students')),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('bio', models.TextField()),
                ('birthday', models.DateField()),
                ('classes', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('social_accounts', models.ManyToManyField(to='students.socialaccount')),
            ],
        ),
    ]
