# Generated by Django 5.1.1 on 2024-09-05 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='classes',
        ),
    ]
