# Generated by Django 5.1.1 on 2024-09-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_student_classes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='bio',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='social_accounts',
            field=models.ManyToManyField(blank=True, to='students.socialaccount'),
        ),
    ]
