# Generated by Django 5.1.1 on 2024-10-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_bio_alter_student_birthday_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socialaccount',
            name='username',
        ),
        migrations.AlterField(
            model_name='socialaccount',
            name='social_media',
            field=models.CharField(choices=[('snapchat', 'Snapchat'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('facebook', 'Facebook'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('pinterest', 'Pinterest'), ('github', 'Github')], max_length=100),
        ),
    ]
